### 1. Register a new user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "lordBucket",
  "email": "antoniuk.orest@gmail.com",
  "password": "password123"
}

### ------------------------------------
### 2. Login and save the token
# @name loginRequest
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "antoniuk.orest@gmail.com",
  "password": "password123"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### ------------------------------------
### 3. Test a secure endpoint
# This request will automatically use the "auth_token" variable
GET http://localhost:8080/api/languages
Authorization: {{auth_token}}